# Generated by Django 5.2.4 on 2025-07-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="created_at",
            new_name="date_added",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="completed",
            new_name="done",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="title",
            new_name="name",
        ),
    ]
